GET https://search.library.berkeley.edu/primaws/rest/pub/pnxs?blendFacetsSeparately=false&browseParams={%22headingType%22:%22SERIES%22,%22vocabularyCode%22:%22LCNAMES%22,%22normalizedValue%22:%22Estudios+cri%CC%81ticos+de+literatura%22,%22numberOfResults%22:%2220%2B%22,%22displayValue%22:%22Estudios%2FContempora%CC%81nea.%22,%22sourceCode%22:%22UNIFORM_TITLE%22,%22isPrefered%22:false,%22originatingSystem%22:%22LIBRARY_OF_CONGRESS%22,%22browseType%22:%22SERIES%22,%22isGlobal%22:true,%22originatingSystemId%22:%22no2017134578%22,%22family%22:%22MARC21%22,%22recordProvenance%22:%22COMMUNITY%22}&disableCache=false&getMore=0&inst=01UCS_BER&lang=en&limit=10&mode=browse&newspapersActive=false&newspapersSearch=false&offset=0&pcAvailability=true&q=Browse:+Estudios%2FContempora%CC%81nea.&qExclude=&qInclude=&rapido=false&refEntryActive=false&rtaLinks=true&scope=browse_search&skipDelivery=Y&sort=title&tab=default_tab&vid=01UCS_BER:UCB HTTP/1.1